const CONFIG = {
  COMMERCE_COLOR_PRIMARY: '#4169E1',
  COMMERCE_COLOR_BG: '#f5f5f5',
  COMMERCE_COLOR_BG_DARK: '##3B496B',
  COMMERCE_COLOR_CARD_DARK: '#1f2937',
  COMMERCE_COLOR_TEXT_DARK: '#f9fafb',

  // 封面大图
  COMMERCE_HOME_BANNER_ENABLE: true,

  COMMERCE_TEXT_CENTER_TITLE: '心爱的，再会了', // 中间产品区块标题
  COMMERCE_TEXT_CENTER_DESCRIPTION:
    '', // 中间产品区块文字描述
  COMMERCE_TEXT_CENTER_CATEGORY_TITLE: '常春藤蔓', // 左侧产品分类标题
  COMMERCE_TEXT_FOOTER_TITLE: '', // COMMERCE主题页脚文案标题；按Shift+Enter键可以换行
  COMMERCE_TEXT_FOOTER_MENU_1: '', // COMMERCE主题页脚左侧菜单标题1
  COMMERCE_TEXT_FOOTER_MENU_2: '', // COMMERCE主题页脚左侧菜单标题2

  COMMERCE_FOOTER_RIGHT_IMG_URL: null, // 显示页脚右侧的图片，通常放二维码
  COMMERCE_FOOTER_RIGHT_TEXT: null, // 页脚右侧图片下的文字描述

  COMMERCE_HOME_POSTS_COUNT: 9, // 首页展示商品数
  COMMERCE_CONTACT_WHATSAPP_SHOW: false, // 是否展示whatsapp联系按钮 请配置 CONTACT_WHATSAPP
  COMMERCE_CONTACT_TELEGRAM_SHOW: false, // 联系栏展示telegram按钮 请配置 CONTACT_TELEGRAM

  COMMERCE_ARTICLE_COPYRIGHT: true, // 文章版权声明
  COMMERCE_ARTICLE_NOT_BY_AI: false // 显示非AI写作
}
export default CONFIG
